changing the transfer scripts

diff --git a/TOOLS/bin/get-from-hpss b/TOOLS/bin/get-from-hpss
--- a/TOOLS/bin/get-from-hpss
+++ b/TOOLS/bin/get-from-hpss
@@ -1,13 +1,11 @@
 #!/bin/sh
 set -u
+# gets a file quickly to HPSS to use htar, command is
+#   htar -xvf ${ARCHIVE_HOME}/test.tar ${FILES}
 FILE=${1:-$PWD}
 YEAR=${2:-1}
-HTAR=${3:-F}
 
 HSI_DIR=/NCEPDEV/emc-marine/${YEAR}year/Neil.Barton
-if [[ ${HTAR} == T ]]; then
-    hsi mkdir -p ${HSI_DIR}
-    htar -cvf ${HSI_DIR}/test.tar ${FILE}/*
-else
-    hsi get ${HSI_DIR}/${FILE} : ${FILE}
-fi
+echo "GETTING: ${HSI_DIR}/${FILE}"
+hsi -q get ${FILE} : ${HSI_DIR}/${FILE} 2>/dev/null
+(( $? != 0 )) && echo "TRANSFER FAILED: ${HSI_DIR}/${FILE}"
diff --git a/TOOLS/bin/put-to-hera b/TOOLS/bin/put-to-hera
--- a/TOOLS/bin/put-to-hera
+++ b/TOOLS/bin/put-to-hera
@@ -1,6 +1,18 @@
 #!/bin/sh
 set -u
-LOCAL_FILE=${1:-$PWD}
-REMOTE_FOLDER=${2:-/scratch2/NCEPDEV/stmp1/Neil.Barton}
+ARGS=${@}
+LAST_ARG=${@: -1}
+if (( ${#} == 0 )); then
+    echo 'ERROR: files/arguments most be supplied'
+    exit 1
+fi
 
-scp ${LOCAL_FILE} Neil.Barton@dtn-hera.fairmont.rdhpcs.noaa.gov:${REMOTE_FOLDER}
+if [[ -f ${LAST_ARG} ]]; then
+    REMOTE_FOLDER=/scratch2/NCEPDEV/stmp1/Neil.Barton
+    FILES=${@}
+else
+    REMOTE_FOLDER=${LAST_ARG}
+    FILES=${@:1:$(($#-1))}
+fi
+
+scp ${FILES} Neil.Barton@dtn-hera.fairmont.rdhpcs.noaa.gov:${REMOTE_FOLDER}
diff --git a/TOOLS/bin/put-to-hpss b/TOOLS/bin/put-to-hpss
--- a/TOOLS/bin/put-to-hpss
+++ b/TOOLS/bin/put-to-hpss
@@ -1,13 +1,13 @@
 #!/bin/sh
+# sends a file quickly to HPSS to use htar, command is
+#   htar -cvf ${ARCHIVE_HOME}/test.tar ${FILES}
 set -u
 LOCAL_FILE=${1:-$PWD}
 YEAR=${2:-1}
-HTAR=${3:-F}
-
 HSI_DIR=/NCEPDEV/emc-marine/${YEAR}year/Neil.Barton
-if [[ ${HTAR} == T ]]; then
-    hsi mkdir -p ${HSI_DIR}
-    htar -cvf ${HSI_DIR}/test.tar ${LOCAL_FILE}/*
-else
-    hsi put ${LOCAL_FILE} : ${HSI_DIR}/${LOCAL_FILE}
-fi
+
+echo "PUTTING FILE AT: ${HSI_DIR}/${FILE}"
+hsi -q put ${LOCAL_FILE} : ${HSI_DIR}/${LOCAL_FILE} 2>/dev/null
+(( $? != 0 )) && echo "TRANSFER FAILED: ${HSI_DIR}/${FILE}"
+    
+
diff --git a/TOOLS/bin/put-to-orion b/TOOLS/bin/put-to-orion
--- a/TOOLS/bin/put-to-orion
+++ b/TOOLS/bin/put-to-orion
@@ -1,6 +1,18 @@
 #!/bin/sh
 set -u
-LOCAL_FILE=${1:-$PWD}
-REMOTE_FOLDER=${2:-/home/nbarton}
+ARGS=${@}
+LAST_ARG=${@: -1}
+if (( ${#} == 0 )); then
+    echo 'ERROR: files/arguments most be supplied'
+    exit 1
+fi
+
+if [[ -f ${LAST_ARG} ]]; then
+    REMOTE_FOLDER=/home/nbarton
+    FILES=${@}
+else
+    REMOTE_FOLDER=${LAST_ARG}
+    FILES=${@:1:$(($#-1))}
+fi
  
-scp ${LOCAL_FILE} nbarton@orion-dtn.hpc.msstate.edu:${REMOTE_FOLDER} 
+scp ${FILES} nbarton@orion-dtn.hpc.msstate.edu:${REMOTE_FOLDER} 
